# Generated by Django 6.0.3 on 2026-04-19 16:26

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_category_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='products', to='store.category'),
        ),
    ]
