# Generated by Django 6.0.3 on 2026-05-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_cart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_at_addition',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
