# Generated by Django 6.0.3 on 2026-05-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cartitem_price_at_addition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price_at_addition',
        ),
    ]
